#!/bin/bash
#PBS -l walltime=01:30:00
# selecting 1 nodes = 1*4 = 4 processors for use, mpiprocs needs to equal ncpus and doesn't exceed 4
#PBS -l select=1:mpiprocs=4:ncpus=4
# scatter required
#PBS -l place=scatter
# account required
#PBS -A 01TRAN002

cd $PBS_O_WORKDIR
echo "RUNNING ON: `/usr/bin/uniq $PBS_NODEFILE`"
./Allrun
# ./PrepareForParallelRun
# mpirun_jaws -np 8 interDyMFoam -parallel > $WORKDIR/flexible-wall/log
